version: "3.8"
services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    stdin_open: true
    tty: true
volumes:
  bundle:
